-- 기존 테이블과 시퀀스 제거
DROP TABLE BOARD;
DROP TABLE CATEGORY;
DROP SEQUENCE SEQ_BOARD;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD;

-- 1. CATEGORY 테이블 생성
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100)
);

-- 2. BOARD 테이블 생성
CREATE TABLE BOARD(
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(400),
    CATEGORY_NO NUMBER,
    CREATE_AT TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_AT TIMESTAMP DEFAULT SYSDATE,
    DEL_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

-- 3. CATEGORY 더미 데이터 삽입
INSERT INTO CATEGORY VALUES (1, '공지사항');
INSERT INTO CATEGORY VALUES (2, '자유 게시판');
INSERT INTO CATEGORY VALUES (3, 'FAQ');

-- 4. BOARD 더미 데이터 삽입
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_BOARD.NEXTVAL, '첫 번째 게시글', '안녕하세요, 첫 글입니다!', 1);

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_BOARD.NEXTVAL, '두 번째 글', '두 번째 글의 내용입니다.', 2);

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_BOARD.NEXTVAL, '공지사항 안내', '이번 주 금요일에 서버 점검이 있습니다.', 1);

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_BOARD.NEXTVAL, '질문 있습니다', '이 기능은 어떻게 사용하는 건가요?', 3);

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_BOARD.NEXTVAL, '정보 공유', '좋은 사이트 하나 추천드립니다.', 2);

COMMIT;

-- 쿼리문 (BOARD)
-- INSERT 
INSERT INTO BOARD(
    NO
    , TITLE
    , CONTENT
    , CATEGORY_NO
    , CREATE_AT
    , MODIFIED_AT
) VALUES (
    SEQ_BOARD.NEXTVAL
    , 'TITLE 삽입'
    , 'CONTENT 삽입'
    , 1
    , SYSDATE
    , SYSDATE
)
;

-- SELECT
SELECT 
    B.NO
    , B.TITLE
    , B.CONTENT
    , C.CATEGORY_NAME
FROM BOARD B
INNER JOIN CATEGORY C
ON B.CATEGORY_NO = C.CATEGORY_NO
WHERE DEL_YN = 'N'
;

-- SELECT BY NO
SELECT 
    B.NO
    , B.TITLE
    , B.CONTENT
    , C.CATEGORY_NAME
    , B.CREATE_AT
    , B.MODIFIED_AT
FROM BOARD B
INNER JOIN CATEGORY C
ON B.CATEGORY_NO = C.CATEGORY_NO
WHERE DEL_YN = 'N'
AND NO = '1'
;

-- DELETE (NO -> SOFT DELET - DEL_YN = 'Y')
UPDATE BOARD
SET
    DEL_YN = 'Y'
WHERE NO = '1'
;

-- UPDATE (TITLE, CONTENT 수정 - 수정일시 기록)
UPDATE BOARD
SET
    TITLE = '첫 번째 게시물 제목 변경!'
    , CONTENT = '내용도 변경하였습니다.'
    , MODIFIED_AT = SYSDATE
WHERE NO = '1'
AND DEL_YN = 'N'
;